### ISSUE TITLE
rtree dependency needed for 2nd practice

### ISSUE THREAD

**Issue by zipy124** [smartgeometry-ucl/COMP0119_24-25#1]
COMP0119_20-21/tutorials/coding_framework/python/practice/visualize_distance.ipynb : The line ```cl_pts,_,_=trimesh.proximity.closest_point(tm,query)``` requires a dependency on the rtree module.

This should be mentioned in the install file, or noted in the jupyter notebook as its a soft dependency (not explicitly mentioned at the top of the notebook in the import section).

**Comment by yushiangw** [comment]
thanks
these two lines can be commented out or run `pip install rtree`

````
cl_pts,_,_=trimesh.proximity.closest_point(tm,query)
query_on_mesh=np.array(cl_pts).reshape(1,3)
