### ISSUE TITLE
CPP install instructions for cmake execute in the wrong directory

### ISSUE THREAD

**Issue by zipy124** [smartgeometry-ucl/COMP0119_24-25#2]
In the install instructions you are asked to run the command ```cd build_debug; cmake .. -DCMAKE_BUILD_TYPE=Debug``` but this should be ```cd build_debug; cmake ../.. -DCMAKE_BUILD_TYPE=Debug``` since the CMakeLists.txt file is not in the /src/ directory but the parent directory of that.

**Comment by yushiangw** [comment]
thanks
readme file updated
